<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { createEventDispatcher, onDestroy, onMount, getContext } from 'svelte';
	import { config, models, tags as _tags } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';
	import XMark from '$lib/components/icons/XMark.svelte';
	import ChevronRight from '$lib/components/icons/ChevronRight.svelte';
	import {
		getFeedbackDialogState,
		LEGAL_QUALITY_FEEDBACK_CATEGORIES,
		PRODUCT_FEEDBACK_CATEGORIES
	} from '$lib/utils/feedback';
	import type { FeedbackDialogState } from '$lib/utils/feedback';

	const i18n = getContext('i18n');

	const dispatch = createEventDispatcher();

	export let message;
	export let show = false;
	export let saving = false;
	export let error = '';

	let tags = [];

	let comment = '';
	let selectedCategories: string[] = [];

	let detailedRating = null;
	let selectedModel = null;
	let submitted = false;
	let feedbackState: FeedbackDialogState = 'idle';
	let closeTimer: number | null = null;

	$: if (message) {
		init();
	}

	const init = () => {
		if (!comment) {
			comment = message?.annotation?.comment ?? '';
		}

		if (selectedCategories.length === 0) {
			selectedCategories = [...(message?.annotation?.categories ?? [])];
		}

		tags = (message?.annotation?.tags ?? []).map((tag) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = message?.annotation?.details?.rating ?? null;
		}
	};

	$: if (submitted) {
		const nextFeedbackState = getFeedbackDialogState({
			submitted,
			saving,
			error,
			currentState: feedbackState
		});

		if (nextFeedbackState === 'success' && feedbackState !== 'success') {
			feedbackState = 'success';
			toast.success($i18n.t('Thanks for your feedback!'));
			closeTimer = window.setTimeout(() => {
				show = false;
			}, 800);
		} else {
			feedbackState = nextFeedbackState;
		}
	}

	onDestroy(() => {
		if (closeTimer) {
			window.clearTimeout(closeTimer);
		}
	});

	onMount(() => {
		if (message?.arena) {
			selectedModel = $models.find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
				})
			);
		}
	});

	const saveHandler = () => {
		console.log('saveHandler');
		submitted = true;
		feedbackState = 'submitting';

		dispatch('save', {
			reason: selectedCategories[0] ?? '',
			comment: comment,
			free_text: comment,
			categories: selectedCategories,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});
	};

	const toggleCategory = (category: string) => {
		if (selectedCategories.includes(category)) {
			selectedCategories = selectedCategories.filter((item) => item !== category);
		} else {
			selectedCategories = [...selectedCategories, category];
		}
	};
</script>

{#if message?.arena}
	<div class="text-xs font-medium pt-1.5 -mb-0.5">
		{$i18n.t('This response was generated by "{{model}}"', {
			model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
		})}
	</div>
{/if}

<div
	class=" my-2.5 rounded-xl px-4 py-3 border border-gray-100/30 dark:border-gray-850/30"
	id="message-feedback-{message.id}"
>
	<div class="flex justify-between items-center">
		<div class="text-sm font-medium">{$i18n.t('How would you rate this response?')}</div>

		<!-- <div class=" text-sm">{$i18n.t('Tell us more:')}</div> -->

		<button
			aria-label={$i18n.t('Close feedback')}
			on:click={() => {
				show = false;
			}}
		>
			<XMark className={'size-4'} />
		</button>
	</div>

	<div class="w-full flex justify-center">
		<div class=" relative w-fit overflow-x-auto scrollbar-none">
			<div class="mt-1.5 w-fit flex gap-1 pb-2">
				<!-- 1-10 scale -->
				{#each Array.from({ length: 10 }).map((_, i) => i + 1) as rating}
					<button
						aria-label={$i18n.t('Rate {{rating}} out of 10', { rating })}
						class="size-7 text-sm border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {detailedRating ===
						rating
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-full disabled:cursor-not-allowed disabled:text-gray-500 disabled:bg-white dark:disabled:bg-gray-900"
						on:click={() => {
							detailedRating = rating;
						}}
						disabled={message?.annotation?.rating === -1 ? rating > 5 : rating < 6}
					>
						{rating}
					</button>
				{/each}
			</div>

			<div class="sticky top-0 bottom-0 left-0 right-0 flex justify-between text-xs">
				<div>
					1 - {$i18n.t('Awful')}
				</div>

				<div>
					10 - {$i18n.t('Amazing')}
				</div>
			</div>
		</div>
	</div>

	<div class="mt-3">
		<div class="text-sm font-medium">{$i18n.t('What should we improve?')}</div>

		<div class="text-xs text-gray-500 mt-2">{$i18n.t('Product experience')}</div>
		<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
			{#each PRODUCT_FEEDBACK_CATEGORIES as category}
				<button
					type="button"
					class="px-3 py-0.5 border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedCategories.includes(
						category.key
					)
						? 'bg-gray-100 dark:bg-gray-800'
						: ''} transition rounded-xl"
					aria-pressed={selectedCategories.includes(category.key)}
					on:click={() => {
						toggleCategory(category.key);
					}}
				>
					{$i18n.t(category.label)}
				</button>
			{/each}
		</div>

		<div class="text-xs text-gray-500 mt-2.5">{$i18n.t('Work-product quality')}</div>
		<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
			{#each LEGAL_QUALITY_FEEDBACK_CATEGORIES as category}
				<button
					type="button"
					class="px-3 py-0.5 border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedCategories.includes(
						category.key
					)
						? 'bg-gray-100 dark:bg-gray-800'
						: ''} transition rounded-xl"
					aria-pressed={selectedCategories.includes(category.key)}
					on:click={() => {
						toggleCategory(category.key);
					}}
				>
					{$i18n.t(category.label)}
				</button>
			{/each}
		</div>
	</div>

	{#if feedbackState === 'success'}
		<div class="mt-2 text-xs text-green-600 dark:text-green-400">
			{$i18n.t('Thanks for your feedback!')}
		</div>
	{:else if feedbackState === 'error' && error}
		<div class="mt-2 text-xs text-red-600 dark:text-red-400">
			{error}
		</div>
	{/if}

	<div class="mt-2">
		<textarea
			bind:value={comment}
			class="w-full text-sm px-1 py-2 bg-transparent outline-hidden resize-none rounded-xl"
			placeholder={$i18n.t('Feel free to add specific details')}
			aria-label={$i18n.t('Additional feedback comments')}
			rows="3"
		/>
	</div>

	<div class="mt-2 gap-1.5 flex justify-between">
		<div class="flex items-end group">
			<Tags
				{tags}
				suggestionTags={$_tags ?? []}
				on:delete={(e) => {
					tags = tags.filter(
						(tag) =>
							tag.name.replaceAll(' ', '_').toLowerCase() !==
							e.detail.replaceAll(' ', '_').toLowerCase()
					);
				}}
				on:add={(e) => {
					tags = [...tags, { name: e.detail }];
				}}
			/>
		</div>

		<div class="flex gap-1.5">
			<button
				class="px-3.5 py-1.5 text-sm font-medium hover:bg-gray-50 dark:hover:bg-gray-850 transition rounded-full disabled:opacity-60"
				type="button"
				disabled={saving}
				on:click={() => {
					show = false;
				}}
			>
				{$i18n.t('Cancel')}
			</button>

			<button
				class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full disabled:cursor-progress disabled:opacity-60"
				type="button"
				disabled={saving}
				on:click={() => {
					saveHandler();
				}}
			>
				{saving ? $i18n.t('Saving...') : $i18n.t('Save')}
			</button>
		</div>
	</div>

	{#if $config?.features.enable_community_sharing && message?.model}
		<div class="mt-3 pt-3 border-t border-gray-100/30 dark:border-gray-850/30">
			<a
				href={`https://openwebui.com/models?q=${encodeURIComponent(message.model)}`}
				target="_blank"
				class="flex cursor-pointer items-center justify-between hover:bg-gray-50 dark:hover:bg-gray-850 w-full px-3 py-2 rounded-xl transition"
			>
				<div class="self-center">
					<div class="text-sm font-medium">
						{$i18n.t('Leave a public review for {{modelName}}', { modelName: message.model })}
					</div>
					<div class="text-xs text-gray-500">
						{$i18n.t('Help the community discover great models')}
					</div>
				</div>
				<ChevronRight className="size-4" />
			</a>
		</div>
	{/if}
</div>
