"""Malicious ZIP fixture generator for upload_skill_zip security tests.

Run this script directly to (re-)generate the fixture ZIP files in the same
directory.  The files it creates are intentionally NOT committed to the repo
as binary blobs — this script IS the source of truth.

    uv run python backend/open_webui/test/fixtures/skills/_build_fixtures.py

Generated files
---------------
malicious-traversal.zip  — path-traversal entry: ../../etc/passwd
malicious-symlink.zip    — Unix symlink entry pointing at /etc/passwd
malicious-absolute.zip   — absolute-path entry: /etc/passwd
happy-control.zip        — minimal valid skill ZIP (safe, should be accepted)

Threat model encoded
--------------------
1. Zip-slip / path traversal: relative paths with ``..`` components that escape
   the extraction root when ``extractall()`` is called naively.
2. Symlink escape: a ZIP entry whose Unix mode bits mark it as a symlink.
   After extraction the symlink points outside the extraction root.
3. Absolute-path injection: a ZIP entry whose name is an absolute path that
   ``extractall()`` would write to the filesystem root on some platforms.
4. Happy-path control: proves that the guards do not block legitimate uploads.

This script uses only stdlib so it has zero dependencies.
"""

import io
import os
import zipfile
from pathlib import Path

_HERE = Path(__file__).parent


def _write(name: str, data: bytes) -> None:
    out = _HERE / name
    out.write_bytes(data)
    print(f'  wrote {out.name} ({len(data)} bytes)')


def build_traversal() -> bytes:
    """Entry with a ``..``-component name that escapes the extraction root."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', compression=zipfile.ZIP_STORED) as zf:
        info = zipfile.ZipInfo('../../etc/passwd')
        info.external_attr = 0o100644 << 16  # regular file mode
        zf.writestr(info, 'root:x:0:0:root:/root:/bin/bash\n')
    return buf.getvalue()


def build_symlink() -> bytes:
    """Entry with Unix symlink mode bits (S_IFLNK = 0o120000).

    The content of the entry is the symlink *target* path, which is how the
    ZIP format encodes symlinks.  On extraction, a naïve extractor creates a
    real filesystem symlink pointing at ``/etc/passwd``.
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', compression=zipfile.ZIP_STORED) as zf:
        info = zipfile.ZipInfo('evil-link')
        # S_IFLNK (0o120000) | rwxrwxrwx (0o777) = 0o120777
        info.external_attr = 0o120777 << 16
        zf.writestr(info, '/etc/passwd')
    return buf.getvalue()


def build_absolute() -> bytes:
    """Entry whose name is an absolute POSIX path."""
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', compression=zipfile.ZIP_STORED) as zf:
        info = zipfile.ZipInfo('/etc/passwd')
        info.external_attr = 0o100644 << 16
        zf.writestr(info, 'root:x:0:0:root:/root:/bin/bash\n')
    return buf.getvalue()


def build_happy_control() -> bytes:
    """Minimal valid skill ZIP that the upload endpoint should accept.

    Structure:
      SKILL.md          — frontmatter with name + description
      tool.py           — a stub Python file
    """
    skill_md = (
        '---\n'
        'name: happy-control-skill\n'
        'description: Fixture generated by _build_fixtures.py for CI testing\n'
        'tags: [testing]\n'
        '---\n\n'
        '# happy-control-skill\n\n'
        'Generated fixture — do not use in production.\n'
    )
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
        for name, content, mode in [
            ('SKILL.md', skill_md, 0o100644),
            ('tool.py', '# stub\ndef run(): pass\n', 0o100644),
        ]:
            info = zipfile.ZipInfo(name)
            info.external_attr = mode << 16
            zf.writestr(info, content)
    return buf.getvalue()


def main() -> None:
    print('Building malicious ZIP fixtures...')
    _write('malicious-traversal.zip', build_traversal())
    _write('malicious-symlink.zip', build_symlink())
    _write('malicious-absolute.zip', build_absolute())
    _write('happy-control.zip', build_happy_control())
    print('Done.')


if __name__ == '__main__':
    main()
